# Generated by Django 2.1.7 on 2019-10-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, upload_to='complaint-images/'),
        ),
    ]
