# Generated by Django 2.1.7 on 2019-10-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_billpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='reg_no',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
